# Site settings
email: "ismaelbacha@hotmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Ismael Bakkali
description:
url: ""
default_img:
home_img: "https://unsplash.com/?photo=x2Tmfd1-SgA"

# Profile settings
name: Ismael Bakkali
profile_img: "http://i.imgur.com/GfewA2t.jpg"
profile: "I'm a London-based Full Stack Developer, with a background in Telecommunications Engineering and Network Marketing."

social:
  github: "https://www.github.com/ismaelocaramelo"
  linkedin: "https://www.linkedin.com/in/ismaelbakkali/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
