# Site settings
email: "ismaelbacha@hotmail.com"
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Ismael Bakkali
description:
url: ""
default_img:
home_img: "https://images.unsplash.com/photo-1472341581053-2af63cb175d4?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&s=8ddab9b3ae5407027aa2da624f71282c"

# Profile settings
name: Ismael Bakkali
profile_img: "https://pbs.twimg.com/profile_images/780714859700883456/E1vI9fK6.jpg"
profile: I'm a London-based Full Stack Developer, with a background in Telecommunications Engineering and Network Marketing.
social:
  github: "https://www.github.com/ismaelocaramelo"
  linkedin: "https://www.linkedin.com/in/ismaelbakkali/"

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
